### ISSUE TITLE
Hacktoberfest 2021 PR Repo.

### ISSUE THREAD

**Issue by cureofdeath** [cureofdeath/PyTodo#4]
We are open to accept PR's

**Comment by arushmangal** [comment]
Hey! Please assign me this issue! I'd be happy to send PRs regarding Python!

**Comment by evansusu** [comment]
I am willing to work on this, please assign it to me.
I am thinking of adding more algorithms in python.

**Comment by Noburu-Hasashi** [comment]
Can i add any project?

**Comment by nkhandelwal07** [comment]
Can you add hacktober fest label?

**Comment by khushboorathore10** [comment]
Hi I want to contribute .  
Please assign me this issue @cureofdeath
